### ISSUE TITLE
[버그] pom.xml > ojdbc6 lib 다운로드 

### ISSUE THREAD

**Issue by Hoenir-Kim** [5omcat/Main_repo#2]
강의 때는 dependency에 추가해도 자동으로 안받아지고 연결이 안되서

디렉토리에 접근해서 새로 다운받는게 아니라

 가지고 있던 ojdbc jar파일을 강제로 넣어놓았었죠

이유는 maven 중앙저장소에서 ojdbc6를 제공하지 않기 때문이었습니다.

`	<repositories>  
		<repository>  
			<id>Spring Plugins</id>  
			<url>http://repo.spring.io/plugins-release/</url>  
		</repository>  
	</repositories>`
 
이제는 번거롭게 강제로 넣지말고 위 코드를 넣어 해결할수있습니다.

이것은 dependencies의 내부가 아닌 바깥 영역에 넣어주면 됩니다.

**Comment by 1eedaegon** [comment]
짜잔
