### ISSUE TITLE
이렇게???

### ISSUE THREAD

**Issue by eunhye42** [5omcat/Main_repo#7]

**Comment by eunhye42** [comment]
나오나요??? <fmt:formatDate value="${now}" pattern="yyyy-MM-dd" var="today" />
        <fmt:formatDate value="${ivo.expire_date }" pattern="yyyy-MM-dd" var="expire"/>
        <c:when test="${expire == today }">

**Comment by eunhye42** [comment]
에러에러에러

**Comment by Hoenir-Kim** [comment]
< > 이거 모양 누르시면 코드작성되용ㅇ

**Comment by Hoenir-Kim** [comment]
에딧 페이지에서 이렇게 넣을수잇어요
`public String writeCode (){
String likethis = "이렇게유";
return likethis;
}`

**Comment by eunhye42** [comment]
아항 ㅋㅋㅋ`<c:choose>`를 안써서 에러났던 거였어요 ㅋㅋㅋ

이 이슈는 해결됨
